"""initial migration

Revision ID: 29c069958d17
Revises: 2acfcb2f221
Create Date: 2016-06-04 10:10:07.242974

"""

# revision identifiers, used by Alembic.
revision = '29c069958d17'
down_revision = '2acfcb2f221'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
