"""initial migration

Revision ID: 2acfcb2f221
Revises: None
Create Date: 2016-06-04 09:10:23.016356

"""

# revision identifiers, used by Alembic.
revision = '2acfcb2f221'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
