"""initial migration

Revision ID: 5825bf7d16ef
Revises: 29c069958d17
Create Date: 2016-06-04 10:17:12.106679

"""

# revision identifiers, used by Alembic.
revision = '5825bf7d16ef'
down_revision = '29c069958d17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    ### end Alembic commands ###
